from library import check_book
from library import check_author

check_book("The Old Man And The Sea")
check_book("1984")
check_book("Romeo And Juliet")
check_book("Cosa Vuoi Davvero?")
check_book("Awaken The Giant Within")
check_book("The Old Man And The Sea")
check_book("Romeo And Juliet")
check_book("Fakebook")
check_book("The Alchemist")
check_author("Jane Austen")
check_author("Gabriele D Annunzio")
check_author("Emily Henry")
check_author("Taylor Jenkins Reid")
check_author("Kristin Hannah")
check_author("Laura Dave")
check_author("Franz Kafka")
check_author("Roberto Re")
check_author("Gino Pelusi")
