from library import check_book
from library import check_author

check_book("The Old Man And The Sea")
check_book("Romeo And Juliet")
check_book("A Farewell To Arms")
check_book("Cosa Vuoi Davvero?")
check_book("Awake The Giant Within")
check_book("The Old Man and the Sea")
check_book("Romeo and Juliet")
check_book("A Farewell to Arms")
check_book("Cosa vuoi davvero?")
check_book("Intelligenza emotiva")
check_book("People We Meet on Vacation")
check_book("Malibu Rising")
check_book("The Four Winds")
check_book("The Last Thing He Told Me")
check_book("The Lincoln Highway")
check_book("Project Hail Mary")
check_book("Klara and the Sun")
check_book("The Push")
check_book("Beautiful World, Where Are You")
check_book("Apples Never Fall")
check_book("Under the Whispering Door")
check_book("Cloud Cuckoo Land")
check_book("Crying in H Mart: A Memoir")
check_book("Think Again: The Power of Knowing What You Dont Know")
check_book("Between Two Kingdoms: A Memoir of a Life Interrupted")
check_book("The Anthropocene Reviewed")
check_book("How To Avoid A Climate Disaster: The Solutions We Have and the Breakthroughs We Need")
check_book("What Happened To You?: Conversations on Trauma, Resilience, and Healing")
check_book("Empire of Pain: The Secret History of the Sackler Dynasty")
check_book("The Sum of Us: What Racism Costs Everyone and How We Can Prosper Together")

check_author("Jane Austen")
check_author("Gabriele D'Annunzio")
check_author("Emily Henry")
check_author("Taylor Jenkins Reid")
check_author("Kristin Hannah")
check_author("Laura Dave")
check_author("Amor Towles")
check_author("Andry Weir")
check_author("Kazuo Ishiguro")
check_author("Ashley Audrain")
check_author("Sally Rooney")
check_author("Laine Moriarty")
check_author("T.J. Klune")
check_author("Anthony Doerr")
check_author("Michelle Zauner")
check_author("Adam Grant")
check_author("Suleika Jaquad")
check_author("John Green")
check_author("Bill Gates")
check_author("Oprah Winfrey")
check_author("Radden Keefe")
check_author("Heather McGhee")
check_author("Jane Austen")
check_author("Gabriele D'Annunzio")
check_author("Melvin Burgess")
check_author("Omero")
check_author("Franz Kafka")
